/**
 * PetStore API
 * ## PetStore OpenAPI 設計 - バックエンド： Laravel - フロントエンド： Vue
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PetStoreApi);
  }
}(this, function(expect, PetStoreApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PetStoreApi.RequestUserEvalution();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RequestUserEvalution', function() {
    it('should create an instance of RequestUserEvalution', function() {
      // uncomment below and update the code to test RequestUserEvalution
      //var instane = new PetStoreApi.RequestUserEvalution();
      //expect(instance).to.be.a(PetStoreApi.RequestUserEvalution);
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new PetStoreApi.RequestUserEvalution();
      //expect(instance).to.be();
    });

    it('should have the property orderId (base name: "order_id")', function() {
      // uncomment below and update the code to test the property orderId
      //var instance = new PetStoreApi.RequestUserEvalution();
      //expect(instance).to.be();
    });

    it('should have the property orderUserId (base name: "order_user_id")', function() {
      // uncomment below and update the code to test the property orderUserId
      //var instance = new PetStoreApi.RequestUserEvalution();
      //expect(instance).to.be();
    });

    it('should have the property evalution (base name: "evalution")', function() {
      // uncomment below and update the code to test the property evalution
      //var instance = new PetStoreApi.RequestUserEvalution();
      //expect(instance).to.be();
    });

    it('should have the property comment (base name: "comment")', function() {
      // uncomment below and update the code to test the property comment
      //var instance = new PetStoreApi.RequestUserEvalution();
      //expect(instance).to.be();
    });

  });

}));
