/**
 * PetStore API
 * ## PetStore OpenAPI 設計 - バックエンド： Laravel v8.x - フロントエンド： Vue v2.x ,LaravelMix v6.x
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Error500 model module.
 * @module model/Error500
 * @version 0.1.1
 */
class Error500 {
    /**
     * Constructs a new <code>Error500</code>.
     * @alias module:model/Error500
     */
    constructor() { 
        
        Error500.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Error500</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Error500} obj Optional instance to populate.
     * @return {module:model/Error500} The populated <code>Error500</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Error500();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} status
 * @default 'error'
 */
Error500.prototype['status'] = 'error';

/**
 * @member {String} message
 */
Error500.prototype['message'] = undefined;

/**
 * @member {Number} code
 */
Error500.prototype['code'] = undefined;






export default Error500;

