/**
 * PetStore API
 * ## PetStore OpenAPI 設計 - バックエンド： Laravel - フロントエンド： Vue
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrderComment model module.
 * @module model/OrderComment
 * @version 0.1.1
 */
class OrderComment {
    /**
     * Constructs a new <code>OrderComment</code>.
     * @alias module:model/OrderComment
     */
    constructor() { 
        
        OrderComment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderComment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderComment} obj Optional instance to populate.
     * @return {module:model/OrderComment} The populated <code>OrderComment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderComment();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('pet_id')) {
                obj['pet_id'] = ApiClient.convertToType(data['pet_id'], 'Number');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
OrderComment.prototype['id'] = undefined;

/**
 * @member {Number} pet_id
 */
OrderComment.prototype['pet_id'] = undefined;

/**
 * @member {Number} user_id
 */
OrderComment.prototype['user_id'] = undefined;

/**
 * @member {String} name
 */
OrderComment.prototype['name'] = undefined;

/**
 * @member {String} avatar
 */
OrderComment.prototype['avatar'] = undefined;

/**
 * @member {String} comment
 */
OrderComment.prototype['comment'] = undefined;

/**
 * @member {String} created_at
 */
OrderComment.prototype['created_at'] = undefined;

/**
 * @member {String} updated_at
 */
OrderComment.prototype['updated_at'] = undefined;






export default OrderComment;

