/**
 * PetStore API
 * ## PetStore OpenAPI 設計 - バックエンド： Laravel - フロントエンド： Vue
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrderInventory model module.
 * @module model/OrderInventory
 * @version 0.1.1
 */
class OrderInventory {
    /**
     * Constructs a new <code>OrderInventory</code>.
     * @alias module:model/OrderInventory
     */
    constructor() { 
        
        OrderInventory.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderInventory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderInventory} obj Optional instance to populate.
     * @return {module:model/OrderInventory} The populated <code>OrderInventory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderInventory();

            if (data.hasOwnProperty('available')) {
                obj['available'] = ApiClient.convertToType(data['available'], 'Number');
            }
            if (data.hasOwnProperty('pending')) {
                obj['pending'] = ApiClient.convertToType(data['pending'], 'Number');
            }
            if (data.hasOwnProperty('sold')) {
                obj['sold'] = ApiClient.convertToType(data['sold'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} available
 */
OrderInventory.prototype['available'] = undefined;

/**
 * @member {Number} pending
 */
OrderInventory.prototype['pending'] = undefined;

/**
 * @member {Number} sold
 */
OrderInventory.prototype['sold'] = undefined;






export default OrderInventory;

