/**
 * PetStore API
 * ## Swagger PetStore  実装 - バックエンド： Laravel - フロントエンド： Vue
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Pet from './Pet';
import User from './User';

/**
 * The Order model module.
 * @module model/Order
 * @version 0.1.1
 */
class Order {
    /**
     * Constructs a new <code>Order</code>.
     * @alias module:model/Order
     */
    constructor() { 
        
        Order.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Order} obj Optional instance to populate.
     * @return {module:model/Order} The populated <code>Order</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Order();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('pet')) {
                obj['pet'] = Pet.constructFromObject(data['pet']);
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = User.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('shop_date')) {
                obj['shop_date'] = ApiClient.convertToType(data['shop_date'], 'String');
            }
            if (data.hasOwnProperty('complete')) {
                obj['complete'] = ApiClient.convertToType(data['complete'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Order.prototype['id'] = undefined;

/**
 * @member {module:model/Pet} pet
 */
Order.prototype['pet'] = undefined;

/**
 * @member {module:model/User} user
 */
Order.prototype['user'] = undefined;

/**
 * @member {Number} quantity
 * @default 1
 */
Order.prototype['quantity'] = 1;

/**
 * @member {Number} status
 */
Order.prototype['status'] = undefined;

/**
 * @member {String} shop_date
 */
Order.prototype['shop_date'] = undefined;

/**
 * @member {Boolean} complete
 * @default false
 */
Order.prototype['complete'] = false;






export default Order;

