/**
 * PetStore API
 * ## Swagger PetStore  実装 - バックエンド： Laravel - フロントエンド： Vue
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequestAuthLogin model module.
 * @module model/RequestAuthLogin
 * @version 0.1.1
 */
class RequestAuthLogin {
    /**
     * Constructs a new <code>RequestAuthLogin</code>.
     * @alias module:model/RequestAuthLogin
     * @param email {String} 
     * @param password {String} 
     */
    constructor(email, password) { 
        
        RequestAuthLogin.initialize(this, email, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, password) { 
        obj['email'] = email;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>RequestAuthLogin</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestAuthLogin} obj Optional instance to populate.
     * @return {module:model/RequestAuthLogin} The populated <code>RequestAuthLogin</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestAuthLogin();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} email
 */
RequestAuthLogin.prototype['email'] = undefined;

/**
 * @member {String} password
 */
RequestAuthLogin.prototype['password'] = undefined;






export default RequestAuthLogin;

