/**
 * PetStore API
 * ## PetStore OpenAPI 設計 - バックエンド： Laravel v8.x - フロントエンド： Vue v2.x ,LaravelMix v6.x
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Category from './Category';
import Tag from './Tag';

/**
 * The RequestPetUpdate model module.
 * @module model/RequestPetUpdate
 * @version 0.1.1
 */
class RequestPetUpdate {
    /**
     * Constructs a new <code>RequestPetUpdate</code>.
     * @alias module:model/RequestPetUpdate
     * @param id {Number} 
     * @param name {String} 
     */
    constructor(id, name) { 
        
        RequestPetUpdate.initialize(this, id, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name) { 
        obj['id'] = id;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>RequestPetUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestPetUpdate} obj Optional instance to populate.
     * @return {module:model/RequestPetUpdate} The populated <code>RequestPetUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestPetUpdate();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = Category.constructFromObject(data['category']);
            }
            if (data.hasOwnProperty('photo_urls')) {
                obj['photo_urls'] = ApiClient.convertToType(data['photo_urls'], ['String']);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [Tag]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
RequestPetUpdate.prototype['id'] = undefined;

/**
 * @member {String} name
 */
RequestPetUpdate.prototype['name'] = undefined;

/**
 * @member {module:model/Category} category
 */
RequestPetUpdate.prototype['category'] = undefined;

/**
 * @member {Array.<String>} photo_urls
 */
RequestPetUpdate.prototype['photo_urls'] = undefined;

/**
 * @member {Array.<module:model/Tag>} tags
 */
RequestPetUpdate.prototype['tags'] = undefined;






export default RequestPetUpdate;

