/**
 * PetStore API
 * ## PetStore OpenAPI 設計 - バックエンド： Laravel - フロントエンド： Vue
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequestOrderUpdate model module.
 * @module model/RequestOrderUpdate
 * @version 0.1.1
 */
class RequestOrderUpdate {
    /**
     * Constructs a new <code>RequestOrderUpdate</code>.
     * @alias module:model/RequestOrderUpdate
     * @param petId {Number} 
     * @param status {Number} 
     */
    constructor(petId, status) { 
        
        RequestOrderUpdate.initialize(this, petId, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, petId, status) { 
        obj['pet_id'] = petId;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>RequestOrderUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestOrderUpdate} obj Optional instance to populate.
     * @return {module:model/RequestOrderUpdate} The populated <code>RequestOrderUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestOrderUpdate();

            if (data.hasOwnProperty('pet_id')) {
                obj['pet_id'] = ApiClient.convertToType(data['pet_id'], 'Number');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('ship_date')) {
                obj['ship_date'] = ApiClient.convertToType(data['ship_date'], 'String');
            }
            if (data.hasOwnProperty('complete')) {
                obj['complete'] = ApiClient.convertToType(data['complete'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} pet_id
 */
RequestOrderUpdate.prototype['pet_id'] = undefined;

/**
 * @member {Number} quantity
 * @default 1
 */
RequestOrderUpdate.prototype['quantity'] = 1;

/**
 * @member {Number} status
 */
RequestOrderUpdate.prototype['status'] = undefined;

/**
 * @member {String} ship_date
 */
RequestOrderUpdate.prototype['ship_date'] = undefined;

/**
 * @member {Boolean} complete
 * @default false
 */
RequestOrderUpdate.prototype['complete'] = false;






export default RequestOrderUpdate;

