/**
 * PetStore API
 * ## PetStore OpenAPI 設計 - バックエンド： Laravel - フロントエンド： Vue
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequestAuthRegister model module.
 * @module model/RequestAuthRegister
 * @version 0.1.1
 */
class RequestAuthRegister {
    /**
     * Constructs a new <code>RequestAuthRegister</code>.
     * @alias module:model/RequestAuthRegister
     * @param name {String} 
     * @param email {String} 
     * @param password {String} 
     */
    constructor(name, email, password) { 
        
        RequestAuthRegister.initialize(this, name, email, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, email, password) { 
        obj['name'] = name;
        obj['email'] = email;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>RequestAuthRegister</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestAuthRegister} obj Optional instance to populate.
     * @return {module:model/RequestAuthRegister} The populated <code>RequestAuthRegister</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestAuthRegister();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
RequestAuthRegister.prototype['name'] = undefined;

/**
 * @member {String} email
 */
RequestAuthRegister.prototype['email'] = undefined;

/**
 * @member {String} password
 */
RequestAuthRegister.prototype['password'] = undefined;






export default RequestAuthRegister;

