/**
 * PetStore API
 * ## PetStore OpenAPI 設計 - バックエンド： Laravel - フロントエンド： Vue
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequestOrderStore model module.
 * @module model/RequestOrderStore
 * @version 0.1.1
 */
class RequestOrderStore {
    /**
     * Constructs a new <code>RequestOrderStore</code>.
     * @alias module:model/RequestOrderStore
     * @param petId {Number} 
     * @param quantity {Number} 
     * @param status {Number} 
     */
    constructor(petId, quantity, status) { 
        
        RequestOrderStore.initialize(this, petId, quantity, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, petId, quantity, status) { 
        obj['pet_id'] = petId;
        obj['quantity'] = quantity || 1;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>RequestOrderStore</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestOrderStore} obj Optional instance to populate.
     * @return {module:model/RequestOrderStore} The populated <code>RequestOrderStore</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestOrderStore();

            if (data.hasOwnProperty('pet_id')) {
                obj['pet_id'] = ApiClient.convertToType(data['pet_id'], 'Number');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} pet_id
 */
RequestOrderStore.prototype['pet_id'] = undefined;

/**
 * @member {Number} quantity
 * @default 1
 */
RequestOrderStore.prototype['quantity'] = 1;

/**
 * @member {Number} status
 */
RequestOrderStore.prototype['status'] = undefined;






export default RequestOrderStore;

