/**
 * PetStore API
 * ## PetStore OpenAPI 設計 - バックエンド： Laravel - フロントエンド： Vue
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ResponsePeginationLinks model module.
 * @module model/ResponsePeginationLinks
 * @version 0.1.1
 */
class ResponsePeginationLinks {
    /**
     * Constructs a new <code>ResponsePeginationLinks</code>.
     * @alias module:model/ResponsePeginationLinks
     */
    constructor() { 
        
        ResponsePeginationLinks.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ResponsePeginationLinks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponsePeginationLinks} obj Optional instance to populate.
     * @return {module:model/ResponsePeginationLinks} The populated <code>ResponsePeginationLinks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponsePeginationLinks();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} url
 */
ResponsePeginationLinks.prototype['url'] = undefined;

/**
 * @member {String} label
 */
ResponsePeginationLinks.prototype['label'] = undefined;

/**
 * @member {Boolean} active
 */
ResponsePeginationLinks.prototype['active'] = undefined;






export default ResponsePeginationLinks;

