/**
 * PetStore API
 * ## PetStore OpenAPI 設計 - バックエンド： Laravel - フロントエンド： Vue
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ResponseOk model module.
 * @module model/ResponseOk
 * @version 0.1.1
 */
class ResponseOk {
    /**
     * Constructs a new <code>ResponseOk</code>.
     * @alias module:model/ResponseOk
     * @param ok {Boolean} 
     */
    constructor(ok) { 
        
        ResponseOk.initialize(this, ok);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ok) { 
        obj['ok'] = ok;
    }

    /**
     * Constructs a <code>ResponseOk</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseOk} obj Optional instance to populate.
     * @return {module:model/ResponseOk} The populated <code>ResponseOk</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ResponseOk();

            if (data.hasOwnProperty('ok')) {
                obj['ok'] = ApiClient.convertToType(data['ok'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} ok
 */
ResponseOk.prototype['ok'] = undefined;






export default ResponseOk;

