/**
 * PetStore API
 * ## PetStore OpenAPI 設計 - バックエンド： Laravel v8.x - フロントエンド： Vue v2.x ,LaravelMix v6.x
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Unexpected model module.
 * @module model/Unexpected
 * @version 0.1.1
 */
class Unexpected {
    /**
     * Constructs a new <code>Unexpected</code>.
     * @alias module:model/Unexpected
     */
    constructor() { 
        
        Unexpected.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Unexpected</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Unexpected} obj Optional instance to populate.
     * @return {module:model/Unexpected} The populated <code>Unexpected</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Unexpected();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} status
 * @default 'error'
 */
Unexpected.prototype['status'] = 'error';

/**
 * @member {String} message
 */
Unexpected.prototype['message'] = undefined;

/**
 * @member {Number} code
 */
Unexpected.prototype['code'] = undefined;






export default Unexpected;

